import Head from "next/head";
import Image from "next/image";
import { FaFigma, FaHtml5, FaJava, FaNodeJs, FaReact } from "react-icons/fa";
import { IoLogoJavascript } from "react-icons/io";
import profile from "../public/RObert.jpg";
import hope from "../public/hope.PNG";
import dashboard from "../public/dashboard.PNG";
import karisimbi from "../public/karisimbi.PNG";

import React, { useState } from "react";

export default function Home() {
  const [r, setR] = useState(true);

  return (
    <div className="m-o p-0  box-border">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex bg-orange-400 text-white justify-between p-7">
        <div>
          <ul className="flex ">
            <li className="ml-8">
              <a href="#home">Home</a>
            </li>
            <li className="ml-8">
              <a href="#about">About</a>
            </li>
            <li className="ml-8">
              <a href="#portfolio">Portfolio</a>
            </li>
            <li className="ml-8">
              <a href="#blog">Blog</a>
            </li>
            <li className="ml-8">
              <a href="#contact">Contact </a>
            </li>
          </ul>
        </div>
        <div>
          <button
            id="login"
            className="bg-white px-8 py-2 hover:bg-orange-100 hover:text-orange-400 text-orange-400 outline-none border-none  rounded-md"
          >
            Login
          </button>
        </div>
      </header>
      <main className="">
        <div className="bg-orange-400 p-10  flex items-center">
          <div className="flex justify-end">
            <Image
              className="w-2/3 h-2/3 shadow-md -mb-20  rounded-md "
              src={profile}
            ></Image>
          </div>
          <div className="flex  ml-8 flex-col  text-white ">
            <h2 className="text-5xl font-bold my-2">Robert Nyitanga</h2>
            <p>Full stack developer</p>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Age:</span>
              <span>20</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Phone</span>
              <span>+250787491277</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Email</span>
              <span>robertwilly668@gmail.com</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Address: </span>
              <span>Huye, Southern Rwanda</span>
            </div>
          </div>
        </div>
        <div className="m-20 my-40">
          <h2 className="text-4xl text-orange-400">About me</h2>
          <p className="my-8">
            I am Junior Web developer able to build a Web presence from the
            ground up - from concept, navigation, layout and programming to UX
            and SEO. Skilled at writing well-designed, testable and efficient
            code using current best practices in Web development. Fast learner,
            hard worker and team player who is proficient in an array of
            scripting languages and multimedia Web tools.
          </p>
        </div>
        <div className="">
          <div className="flex justify-center m-8">
            <button
              onClick={() => setR(!r)}
              className={` py-2 px-8  ${
                r ? "bg-white text-orange-400" : " bg-orange-400 text-white"
              } shadow-md hover:shadow-lg  rounded-md`}
            >
              Experience
            </button>
            <button
              onClick={() => setR(!r)}
              className={`py-2 px-8  ${
                !r ? "bg-white text-orange-400" : " bg-orange-400 text-white"
              } shadow-md hover:shadow-lg  ml-8 rounded-md`}
            >
              Education
            </button>
          </div>
          <div className="flex justify-center items-center">
            {r ? (
              <>
                <div className="border-r-4  h-96 flex p-8 flex-col justify-between border-orange-500 rounded-md  border-solid">
                  <div class="date">
                    <p>
                      19 <sup>th</sup> May 2021 - 19 <sup>th</sup> dec 2024
                    </p>
                  </div>
                  <div class="date">
                    19 <sup>th</sup> jan 2017 - 19 <sup>th</sup> oct 2019
                  </div>
                  <div class="date">
                    19 <sup>th</sup> May 2014 - 19 <sup>th</sup> dec 2015
                  </div>
                </div>
                <div className="h-96 flex px-8 flex-col justify-between">
                  <div>
                    <h3 className="font-bold">University of Rwanda</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">Advanced secondary school</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            ) : (
              <>
                <div className="border-r-4  h-96 flex p-8 flex-col justify-between border-orange-500 rounded-md  border-solid">
                  <div>
                    <p>
                      4 <sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                </div>
                <div className="h-96 flex px-8 flex-col justify-between">
                  <div>
                    <h3 className="font-bold">
                      Software engineering internership at Andela
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">Romalice consulting Group</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
        <div>
          <h2 className="text-4xl m-20 my-20 text-orange-400 ">
            General skills
          </h2>
        </div>
        <div className="grid grid-cols-3  auto-cols-max place-items-center  gap-4">
          <div className="flex justify-between px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">React,Redux</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span className="text-center">
                <FaReact className="text-4xl text-blue-500" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">JavaScript</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <IoLogoJavascript className="text-4xl text-yellow-600" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">HTML,CSS</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaHtml5 className="text-4xl text-blue-500" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">Java JSP Servelt</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaJava className="text-4xl text-red-500" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">NodeJS</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaNodeJs className="text-4xl text-green-800" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">Figma</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaFigma className="text-4xl text-blue-500" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">NodeJS</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaNodeJs className="text-4xl text-green-800" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">Figma</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaFigma className="text-4xl text-blue-500" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">NodeJS</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaNodeJs className="text-4xl text-green-800" />
              </span>
            </div>
          </div>
          <div className="flex  px-8 py-4   ">
            <div className="flex flex-col mr-4 justify-center">
              <span className="font-semibold text-xl">Figma</span>
              <span className="text-" style={{ fontSize: "10px" }}>
                1 year, 5 projects
              </span>
            </div>
            <div>
              <span>
                <FaFigma className="text-4xl text-blue-500" />
              </span>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-4xl m-20 my-20 text-orange-400 ">My Projects</h2>
        </div>
        <div class="projects">
          <div className="flex m-20">
            <button className="">All</button>
            <button className="ml-8">Webistes</button>
            <button className="ml-8">Mobile</button>
            <button className="ml-8">Games</button>
          </div>
          <div className="flex bg-white h-full rounded-md shadow-md  mx-20">
            <div className="basis-2/5 ">
              <Image
                className="h-full object-cover"
                src={dashboard}
                alt="dashboard  screen shot"
              ></Image>
            </div>
            <div className="basis-3/5 px-6 py-8">
              <div>
                <h2 className="text-2xl  font-semibold">
                  Webiste admin dashboard
                </h2>
                <p className="py-4">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Quaerat eligendi distinctio aliquid odio nostrum architecto
                  sed sequi iusto, hic iure quia, vitae animi tempore eius
                  pariatur doloribus, debitis et quasi.
                </p>
              </div>
              <div>
                <h4 className="font-semibold">Used stack</h4>
                <div className="flex my-8">
                  <button className="bg-white  shadow-md py-2 px-8  rounded-md text-center">
                    React
                  </button>
                  <button className="bg-white  shadow-md py-2 px-8 ml-4 rounded-md text-center">
                    Redux
                  </button>
                  <button className="bg-white  shadow-md py-2 px-8 ml-4 rounded-md text-center">
                    Nodejs
                  </button>
                  <button className="bg-white  shadow-md py-2 px-8 ml-4 rounded-md text-center">
                    Tailwindcss
                  </button>
                </div>
                <div className="text-right  text-blue-600 m-0">
                  <a href="#">lorem.com</a>
                </div>
              </div>
            </div>
          </div>
          <div class="single"></div>
          <div class="single"></div>
        </div>

        <div class="blogs">
          <div>
            <h2 className="text-4xl m-20 my-20 text-orange-400 ">
              Latest blogs
            </h2>
          </div>
          <div className="flex gap-8 m-20">
            <div className="bg-white basis-1/3  rounded-md hover:shadow-lg flex flex-col shadow-md">
              <div className="basis-2/3">
                <Image
                  className="h-80  object-cover"
                  src={karisimbi}
                  alt="atlp program image"
                />
              </div>
              <div className="p-4 basis-1/3 ">
                <div class="date">
                  <span style={{ fontSize: "10px" }}>24 dec 2020</span>
                </div>
                <div className="pb-4">
                  <a href="#">
                    <h4 className="font-semibold text-xl my-4">
                      My Journey through ATLP
                    </h4>
                    <p className="text-sm">
                      Lorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusmLorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusm
                    </p>
                  </a>
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </main>
      <footer>
        <div></div>
        <div></div>
      </footer>
    </div>
  );
}
