import Head from "next/head";
import Image from "next/image";
import profile from "../public/RObert.jpg";

import React, { useState } from "react";

export default function Home() {
  const [r, setR] = useState(true);

  return (
    <div className="m-o p-0  box-border">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex bg-orange-400 text-white justify-between p-7">
        <div>
          <ul className="flex ">
            <li className="ml-8">
              <a href="#home">Home</a>
            </li>
            <li className="ml-8">
              <a href="#about">About</a>
            </li>
            <li className="ml-8">
              <a href="#portfolio">Portfolio</a>
            </li>
            <li className="ml-8">
              <a href="#blog">Blog</a>
            </li>
            <li className="ml-8">
              <a href="#contact">Contact </a>
            </li>
          </ul>
        </div>
        <div>
          <button
            id="login"
            className="bg-white px-8 py-2 hover:bg-orange-100 hover:text-orange-400 text-orange-400 outline-none border-none  rounded-md"
          >
            Login
          </button>
        </div>
      </header>
      <main className="">
        <div className="bg-orange-400 p-10  flex items-center">
          <div className="flex justify-end">
            <Image
              className="w-2/3 h-2/3 shadow-md -mb-20  rounded-md "
              src={profile}
            ></Image>
          </div>
          <div className="flex  ml-8 flex-col  text-white ">
            <h2 className="text-5xl font-bold my-2">Robert Nyitanga</h2>
            <p>Full stack developer</p>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Age:</span>
              <span>20</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Phone</span>
              <span>+250787491277</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Email</span>
              <span>robertwilly668@gmail.com</span>
            </div>
            <div className="flex my-2 justify-between w-4/5">
              <span className="font-bold">Address: </span>
              <span>Huye, Southern Rwanda</span>
            </div>
          </div>
        </div>
        <div className="m-20 my-40">
          <h2 className="text-4xl text-orange-400">About me</h2>
          <p className="my-8">
            I am Junior Web developer able to build a Web presence from the
            ground up - from concept, navigation, layout and programming to UX
            and SEO. Skilled at writing well-designed, testable and efficient
            code using current best practices in Web development. Fast learner,
            hard worker and team player who is proficient in an array of
            scripting languages and multimedia Web tools.
          </p>
        </div>
        <div className="">
          <div className="flex justify-center m-8">
            <button
              onClick={() => setR(!r)}
              className={` py-2 px-8  ${
                r ? "bg-white text-orange-400" : " bg-orange-400 text-white"
              } shadow-md hover:shadow-lg  rounded-md`}
            >
              Experience
            </button>
            <button
              onClick={() => setR(!r)}
              className={`py-2 px-8  ${
                !r ? "bg-white text-orange-400" : " bg-orange-400 text-white"
              } shadow-md hover:shadow-lg  ml-8 rounded-md`}
            >
              Education
            </button>
          </div>
          <div className="flex justify-center items-center">
            {r ? (
              <>
                <div className="border-r-4  h-96 flex p-8 flex-col justify-between border-orange-500 rounded-md  border-solid">
                  <div class="date">
                    <p>
                      19 <sup>th</sup> May 2021 - 19 <sup>th</sup> dec 2024
                    </p>
                  </div>
                  <div class="date">
                    19 <sup>th</sup> jan 2017 - 19 <sup>th</sup> oct 2019
                  </div>
                  <div class="date">
                    19 <sup>th</sup> May 2014 - 19 <sup>th</sup> dec 2015
                  </div>
                </div>
                <div className="h-96 flex px-8 flex-col justify-between">
                  <div>
                    <h3 className="font-bold">University of Rwanda</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">Advanced secondary school</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            ) : (
              <>
                <div className="border-r-4  h-96 flex p-8 flex-col justify-between border-orange-500 rounded-md  border-solid">
                  <div>
                    <p>
                      4 <sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                </div>
                <div className="h-96 flex px-8 flex-col justify-between">
                  <div>
                    <h3 className="font-bold">
                      Software engineering internership at Andela
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">Romalice consulting Group</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-bold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
        <div>
          <h2 className="text-4xl m-20 my-20 text-orange-400 ">
            General skills
          </h2>
        </div>
        <div className="grid grid-cols-3  place-items-center  gap-4">
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <div>  
            <span>JavaScript</span>
            <span>1 year, 5 projects</span>
            </div>
            <div>
            <span></span>
            </div>
          </div>
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <div>
            <span>JavaScript</span>
            <span>2 year, 12 projects</span>
            </div>
            <div>
            <span></span>
            </div>
          </div>
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <div>
            <span>Java JSP Servelt</span>
            <span></span>
            </div>
            <span></span>
          </div>
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <div>
              <span>React redux</span>
              <span>2 year, 12 projects</span>
            </div>
            <span></span>
          </div>
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <span>Figma (UI,UX DESIGN)</span>
            <span>2 year, 12 projects</span>
            <span></span>
          </div>
          <div className="flex flex-col px-8 py-6   bg-white shadow-md">
            <span>Nodejs</span>
            <span>2 year, 12 projects</span>
            <span></span>
          </div>
        </div>

        <div class="projects">
          <div>
            <button>All</button>
            <button>Webistes</button>
            <button>Mobile</button>
            <button>Games</button>
          </div>
          <div class="single">
            <div class="img">
              <img src="" alt="project" />
            </div>
            <div>
              <div>
                <h2>Webiste admin dashboard</h2>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Quaerat eligendi distinctio aliquid odio nostrum architecto
                  sed sequi iusto, hic iure quia, vitae animi tempore eius
                  pariatur doloribus, debitis et quasi.
                </p>
              </div>
              <div>
                <h4>Used stack</h4>
                <div>
                  <button>React</button>
                  <button>Redux</button>
                  <button>Nodejs</button>
                  <button>Tailwindcss</button>
                </div>
                <div>lorem.com</div>
              </div>
            </div>
          </div>
          <div class="single"></div>
          <div class="single"></div>
        </div>

        <div class="blogs">
          <h2>Latest post</h2>
          <div class="listBlog">
            <div class="single">
              <div class="img">
                <img src="/img/andeal.jfif" alt="atlp program image" />
              </div>
              <div class="date">
                <span>24 dec 2020</span>
              </div>
              <div>
                <a href="#">
                  <h4>My Journey through ATLP</h4>
                  <p>
                    Lorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                    ipusmLorem ipusmLorem ipusmLorem ipusmLorem ipusm
                  </p>
                </a>
              </div>
            </div>
            <div class="single">
              <div class="single">
                <div class="img">
                  <img src="/img/andeal.jfif" alt="atlp program image" />
                </div>
                <div class="date">
                  <span>24 dec 2020</span>
                </div>
                <div>
                  <a href="#">
                    <h4>My Journey through ATLP</h4>
                    <p>
                      Lorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusmLorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusm
                    </p>
                  </a>
                </div>
              </div>
            </div>
            <div class="single">
              <div class="single">
                <div class="img">
                  <img src="/img/andeal.jfif" alt="atlp program image" />
                </div>
                <div class="date">
                  <span>24 dec 2020</span>
                </div>
                <div>
                  <a href="#">
                    <h4>My Journey through ATLP</h4>
                    <p>
                      Lorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusmLorem ipusmLorem ipusmLorem ipusmLorem ipusmLorem
                      ipusm
                    </p>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer>
        <div></div>
        <div></div>
      </footer>
    </div>
  );
}
