import Head from "next/head";
import Image from "next/image";
import { FaFigma, FaHtml5, FaJava, FaNodeJs, FaReact } from "react-icons/fa";
import { IoLogoJavascript } from "react-icons/io";
import { FiMenu } from "react-icons/fi";

import { AnimatePresence, motion } from "framer-motion";
import profile from "/public/RObert.jpg";

import React, { use, useState } from "react";
import Footer from "../components/Footer";
import Project from "../components/Project";
import Blog from "../components/Blog";
import Skill from "../components/Skill";
import skills from "../components/data/skills";
import project from "../components/data/project";
import blog from "../components/data/blog";
import Link from "next/link";
import Nav from "../components/Nav";


export default function Home() {
  const [r, setR] = useState(true);
  const [active, setActive] = useState(true);
  const [active1, setActive1] = useState(false);
  const [active2, setActive2] = useState(false);

  const [act, setAct] = useState(false);
  const [projects, setProject] = useState(project);

  return (
    <div className="m-o p-0  box-border">
      <Head>
        <title>Home | Robert portfolio website</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Nav />

      <main
        className="bg-main1"
        style={
          {
            // background: " rgb(2,0,36)",
            // background:
            // "linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,216,155,1) 0%, rgba(25,84,123,1) 100%)",
          }
        }
      >
        <div className="bg-main p-2    md:py-16  flex flex-col  md:flex-row items-center">
          <div className="flex justify-center md:justify-end">
            <Image
              className="w-3/4 md:w-2/3 h-3/4 shadow-md md:-mb-20  rounded-md "
              src={profile}
            ></Image>
          </div>
          <div className="flex  ml-8 flex-col  text-white ">
            <h2 className="text-2xl  md:text-5xl font-bold my-2">
              Robert Nyitanga
            </h2>
            <p>Full stack developer</p>
            <div className="flex my-2 justify-between w-full md:w-4/5">
              <span className="font-semibold">Age:</span>
              <span>20</span>
            </div>
            <div className="flex my-2 justify-between  w-full md:w-4/5">
              <span className="font-semibold">Phone</span>
              <span>+250787491277</span>
            </div>
            <div className="flex my-2 justify-between w-full md:w-4/5">
              <span className="font-semibold">Email</span>
              <span>robertwilly668@gmail.com</span>
            </div>
            <div className="flex my-2 justify-between  w-full md:w-4/5">
              <span className="font-semibold">Address: </span>
              <span>Huye, Southern Rwanda</span>
            </div>
          </div>
        </div>
        <div id="about" className="m-10 md:m-20 my-40">
          <h2 className="text-2xl md:text-4xl text-main  font-semibold">
            About me
          </h2>
          <p className="my-8">
            I am Junior Web developer able to build a Web presence from the
            ground up - from concept, navigation, layout and programming to UX
            and SEO. Skilled at writing well-designed, testable and efficient
            code using current best practices in Web development. Fast learner,
            hard worker and team player who is proficient in an array of
            scripting languages and multimedia Web tools.
          </p>
        </div>
        <div className="">
          <div className="flex justify-center m-8">
            <button
              onClick={() => setR(!r)}
              className={` py-2 px-4 md:px-8  ${
                r ? "bg-white text-main" : " bg-main text-white"
              } shadow-md hover:shadow-lg  rounded-md`}
            >
              Experience
            </button>
            <button
              onClick={() => setR(!r)}
              className={`py-2  px-4 md:px-8 ${
                !r ? "bg-white text-main" : " bg-main text-white"
              } shadow-md hover:shadow-lg  ml-8 rounded-md`}
            >
              Education
            </button>
          </div>
          <div className="flex flex-col  md:flex-row justify-center items-center">
            {r ? (
              <>
                <div className="hidden md:flex md:border-r-4  h-96  p-8 flex-col justify-between border-main rounded-md  border-solid">
                  <div className="hidden md:block">
                    <p>
                      19 <sup>th</sup> May 2021 - 19 <sup>th</sup> dec 2024
                    </p>
                  </div>
                  <div className="hidden md:block">
                    19 <sup>th</sup> jan 2017 - 19 <sup>th</sup> oct 2019
                  </div>
                  <div className="hidden md:block">
                    19 <sup>th</sup> May 2014 - 19 <sup>th</sup> dec 2015
                  </div>
                </div>
                <div className="h-96 flex  px-6 md:px-8 flex-col justify-between">
                  <div className="block py-4 md:hidden">
                    <p>
                      19 <sup>th</sup> May 2021 - 19 <sup>th</sup> dec 2024
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold">University of Rwanda</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div className=" block py-4 md:hidden">
                    19 <sup>th</sup> jan 2017 - 19 <sup>th</sup> oct 2019
                  </div>
                  <div>
                    <h3 className="font-semibold">Advanced secondary school</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div className="block py-4 md:hidden">
                    19 <sup>th</sup> May 2014 - 19 <sup>th</sup> dec 2015
                  </div>
                  <div>
                    <h3 className="font-semibold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            ) : (
              <>
                <div className="hidden md:flex  md:border-r-4  h-96  p-8 flex-col justify-between border-orange-500 rounded-md  border-solid">
                  <div>
                    <p>
                      4 <sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                </div>
                <div className="h-96 flex px-6 md:px-8 flex-col justify-between">
                  <div className="block py-4 md:hidden">
                    <p>
                      4 <sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold">
                      Software engineering internership at Andela
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div className="block py-4 md:hidden">
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold">Romalice consulting Group</h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                  <div className="block py-4 md:hidden">
                    <p>
                      4<sup>th</sup> April 2020 - 5<sup>th</sup> July 2021
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold">
                      ALX Software Engineering Internership
                    </h3>
                    <ul className="list-disc mx-8 my-4 text-sm">
                      <li>Gain Technical and profectional skills</li>
                      <li>Gain Technical and profectional skills</li>
                    </ul>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
        <div>
          <h2 className="text-2xl md:text-4xl m-10 md:m-20 my-20 text-main font-semibold ">
            General skills
          </h2>
        </div>
        <div className="grid  grid-cols-1 sm:grid-cols-2 md:grid-cols-3  auto-cols-max place-items-center  gap-4">
          <Skill skills={skills} />
        </div>
        <div>
          <h2 className=" text-2xl md:text-4xl m-20 my-20 text-main  font-semibold">
            My Projects
          </h2>
        </div>
        <div id="portfolio" className="projects">
          <div
            onClick={() => setAct(true)}
            className="flex text-md  md:text-lg m-20"
          >
            <button
              className={`${active ? "text-main" : ""}  cursor-pointer`}
              onClick={() => {
                setActive(true);
                setActive1(false);
                setActive2(false);
                setProject(project);
              }}
            >
              All
            </button>
            <button
              className={`${active1 ? "text-main" : ""} ml-8 cursor-pointer`}
              onClick={() => {
                setActive(false);
                setActive1(true);
                setActive2(false);
                setProject(project.filter((e) => e.category === "website"));
              }}
            >
              Webistes
            </button>
            <button
              className={`${active2 ? "text-main" : ""} ml-8 cursor-pointer`}
              onClick={() => {
                setActive(false);
                setActive1(false);
                setActive2(true);
                setProject(project.filter((e) => e.category === "mobile"));
              }}
            >
              Mobile
            </button>
            {/* <button
              className="ml-8"
              onClick={() =>
                setProject(project.filter((e) => e.category === "game"))
              }
            >
              Games
            </button> */}
          </div>
          <motion.div layout className="flex flex-col  gap-8">
            <AnimatePresence>
              <Project data={act ? projects : project} />
            </AnimatePresence>
          </motion.div>
        </div>

        <div id="blog" className="blogs">
          <div>
            <h2 className=" text-2xl md:text-4xl m-10 md:m-20 my-20 text-main  font-semibold ">
              Latest blogs
            </h2>
          </div>
          <div className="flex flex-col  md:flex-row gap-8  p-8 md:p-20">
            <Blog data={blog} />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
